name: amilys embyserver latest version

on:
    workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      -
        name: Get Version
        run: |
            docker run --entrypoint cp -v ${PWD}/emby:/data amilys/embyserver:4.8.0.56 /system/EmbyServer.deps.json /data
            LATEST_VERSION=$(grep "EmbyServer" emby/EmbyServer.deps.json | head -n 1 | sed -n 's|.*EmbyServer/\(.*\)":.*|\1|p')
            sed -i "1,40s|amilys_embyserver_latest_version=.*|amilys_embyserver_latest_version=${LATEST_VERSION}|"" all_in_one.sh
            rm -rf ${PWD}/emby

      - 
        uses: stefanzweifel/git-auto-commit-action@be823a7e51f116fecebc222b8307716921375992
        with:
            commit_message: 'chore: update amilys embyserver latest version'
            branch: master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}