name: quark cookie

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "quark_cookie/**"
      - ".github/workflows/quark_cookie.yml"

jobs:
  Windows-amd64:
    runs-on: windows-latest
    name: Build Windows Binary
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Init Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'pip'

      - 
        name: Install Dependent Packages
        run: |
            pip install wheel pyinstaller
            pip install -r requirements.txt
        shell: pwsh
        working-directory: ./quark_cookie

      - 
        name: Pyinstaller
        run: |
            pyinstaller quark_login.spec
        working-directory: ./quark_cookie
        shell: pwsh

      - 
        name: Upload Windows File
        uses: actions/upload-artifact@v3
        with:
            name: quark_login-windows-amd64
            path: quark_cookie/dist/quark_login.exe

  Linux-amd64:
    runs-on: ubuntu-latest
    name: Build Linux Amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'pip'

      - name: Install Dependent Packages
        run: |
            python -m pip install --upgrade pip
            pip install wheel pyinstaller
            pip install -r requirements.txt
        working-directory: ./quark_cookie

      - name: Pyinstaller
        run: |
            pyinstaller quark_login.spec
            mv dist/quark_login dist/quark_login-linux-amd64
        working-directory: ./quark_cookie

      - name: Upload Linux File
        uses: actions/upload-artifact@v3
        with:
            name: quark_login-linux-amd64
            path: quark_cookie/dist/quark_login-linux-amd64

  macos-amd64:
    runs-on: macOS-latest
    name: Build macOS Amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Init Python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'pip'
    
      - name: Install Dependent Packages
        run: |
            python -m pip install --upgrade pip
            pip install wheel pyinstaller
            pip install -r requirements.txt
        working-directory: ./quark_cookie

      - name: Pyinstaller
        run: |
            pyinstaller quark_login.spec
            mv dist/quark_login dist/quark_login-macos-amd64
        working-directory: ./quark_cookie
            
      - name: Upload macOS File
        uses: actions/upload-artifact@v3
        with:
            name: quark_login-macos-amd64
            path: quark_cookie/dist/quark_login-macos-amd64

  Update:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [ Windows-amd64, Linux-amd64, macos-amd64]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Download Artifact
        uses: actions/download-artifact@v3

      - 
        name: Rename
        shell: bash
        run: |
            mkdir releases
            mv ./quark_login-windows-amd64/quark_login.exe ./releases/quark_login-windows-amd64.exe
            mv ./quark_login-macos-amd64/quark_login-macos-amd64 ./releases/quark_login-macos-amd64
            mv ./quark_login-linux-amd64/quark_login-linux-amd64 ./releases/quark_login-linux-amd64

      - 
        name: Upload Release Asset
        uses: dwenegar/upload-release-assets@v3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            release_id: 168891806
            assets_path: |
                ./releases/
